version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "daily"
    target-branch: "dependabot"

  - package-ecosystem: "npm"
    directory: "/backend"
    schedule:
      interval: "daily"
    target-branch: "dependabot"

